 
name: 'chaoxing'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '1 * * * *'
    - cron: '2 * * * *'
    - cron: '3 * * * *'
    - cron: '4 * * * *'
    - cron: '5 * * * *'
    - cron: '6 * * * *'
    - cron: '7 * * * *'
    - cron: '8 * * * *'
    - cron: '9 * * * *'
    - cron: '10 * * * *'
    - cron: '11 * * * *'
    - cron: '12 * * * *'
    - cron: '13 * * * *'
    - cron: '14 * * * *'
    - cron: '15 * * * *'
    - cron: '16 * * * *'
    - cron: '17 * * * *'
    - cron: '18 * * * *'
    - cron: '19 * * * *'
    - cron: '20 * * * *'
    - cron: '21 * * * *'
    - cron: '22 * * * *'
    - cron: '23 * * * *'
    - cron: '24 * * * *'
    - cron: '25 * * * *'
    - cron: '26 * * * *'
    - cron: '27 * * * *'
    - cron: '28 * * * *'
    - cron: '29 * * * *'
    - cron: '30 * * * *'
    - cron: '31 * * * *'
    - cron: '32 * * * *'
    - cron: '33 * * * *'
    - cron: '34 * * * *'
    - cron: '35 * * * *'
    - cron: '36 * * * *'
    - cron: '37 * * * *'
    - cron: '38 * * * *'
    - cron: '39 * * * *'
    - cron: '40 * * * *'
    - cron: '41 * * * *'
    - cron: '42 * * * *'
    - cron: '43 * * * *'
    - cron: '44 * * * *'
    - cron: '45 * * * *'
    - cron: '46 * * * *'
    - cron: '47 * * * *'
    - cron: '48 * * * *'
    - cron: '49 * * * *'
    - cron: '50 * * * *'
    - cron: '51 * * * *'
    - cron: '52 * * * *'
    - cron: '53 * * * *'
    - cron: '54 * * * *'
    - cron: '55 * * * *'
    - cron: '56 * * * *'
    - cron: '57 * * * *'
    - cron: '58 * * * *'
    - cron: '59 * * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Setup python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests
    - name: 'Qiandao'
      env:
        CHAOXING_USERNAME: ${{ secrets.CHAOXING_USERNAME }}
        CHAOXING_PASSWORD: ${{ secrets.CHAOXING_PASSWORD }}
        CHAOXING_SCHOOL: ${{ secrets.CHAOXING_SCHOOL }}
        CHAOXING_SERVER: ${{ secrets.CHAOXING_SERVER }}
        CHAOXING_SERVEROR: ${{ secrets.CHAOXING_SERVEROR }}
      run: python cx.py
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
